FROM node:20-alpine

RUN apk add --no-cache openssl

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

RUN mkdir -p uploads

RUN npx prisma generate

EXPOSE 3001

CMD ["npm", "run", "start:dev"]
